export const portfolioCopy = {
  zh: {
    t0: '主导航',
    t1: '曹进龙',
    t2: '精选项目',
    t3: '关于我',
    t4: '技术能力',
    t5: '联系',
    t6: '专注地图，持续探索',
    t7: '聊聊合作 ↗',
    t8: 'WebGIS 开发者 · 空间探索者',
    t9: '个人作品集 — 2026',
    t10: '为想法绘图。',
    t11: '让世界可见。',
    t12: '让想法拥有坐标。',
    t13: '探索我的作品',
    t14: '查看简历',
    t15: '向下探索',
    t16: '地图开发',
    t17: '数据',
    t18: '可视化表达',
    t19: '全栈',
    t20: '持续探索',
    t21: '地理空间思维',
    t22: '01 / 精选项目',
    t23: '立足真实问题。',
    t24: '用空间来解答。',
    t25: '01 — 海南 / 调查地图',
    t26: '探索这个项目',
    t27: '更多项目实践',
    t28: '个项目',
    t29: '为真实场景而构建。',
    t30: '每一个项目，都是一次探索。',
    t31: '02 / 关于我',
    t32: '以好奇心',
    t33: '作',
    t34: '指南针。',
    t35: '以地图为起点，向更完整的交付前进。',
    t36: '2024.11 — 至今',
    t37: 'WebGIS 开发工程师',
    t38: '湖北嘉款科技有限公司',
    t39: '驻场海南省测绘地理信息局',
    t40: '2022.07 — 09',
    t41: 'WebGIS 开发实习生',
    t42: '武汉中地数码科技有限公司',
    t43: '教育背景',
    t44: '湖北大学',
    t45: '地理信息科学专业 · 2023 年毕业',
    t46: '地图与空间',
    t47: '前端与可视化',
    t48: '后端与工程化 · 持续学习',
    t49: '03 / 有想法，一起聊聊？',
    t50: '期待',
    t51: '与你连接。',
    t52: '聊聊合作',
    t53: '湖北恩施',
    t54: '下载个人简历 ↓',
    t55: '微信二维码 ＋',
    t56: '曹进龙的微信二维码',
    t57: '© 2026 曹进龙 / JINLONG CAO',
    t58: '以好奇心构建，用热爱绘图。',
    p0: '你好，我是曹进龙。专注 WebGIS、三维地图与数据可视化，连接空间数据与真实世界，探索 GIS 全栈开发的更多可能。',
    p1: '从空间数据到业务场景，把复杂问题转化为清晰的产品体验。',
    p2: '毕业于湖北大学地理信息科学专业，持续深耕 WebGIS 前端开发。擅长二维与三维地图、空间可视化，以及复杂业务场景下的交互实现。',
    p3: '目前系统学习并实践 Java、Spring Boot 与 MyBatis，逐步形成覆盖地图应用、后端服务与空间数据的交付能力。',
    p4: '让下一个想法，在地图上发生。欢迎交流 WebGIS、三维可视化与项目合作。',
    features: {
      1: {
        category: '地图应用 · 数据可视化',
        headline: '调查资源，一张图看清。',
        intro: '海南国家调查地图基层网点系统。让调查机构、专业和区域数据汇聚在一张地图上。'
      },
      3: {
        category: '02 / 三维地图 · 空间分析',
        headline: '把空间分析，带入三维。',
        intro: '海南三维项目：从地形分析到地图标绘，构建可交互的三维空间。'
      },
      5: {
        category: '03 / 网站应用 · 知识管理',
        headline: '让专业知识，触手可及。',
        intro: '连接资料、课程与智能问答，一站式构建地籍知识管理与学习体验。'
      }
    }
  },
  en: {
    t0: 'Main navigation',
    t1: 'Jinlong Cao',
    t2: 'Selected work',
    t3: 'About',
    t4: 'Skills',
    t5: 'Contact',
    t6: 'Focused on maps. Always exploring.',
    t7: 'LET’S TALK ↗',
    t8: 'WebGIS Developer · Spatial Explorer',
    t9: 'PORTFOLIO — VOL. 2026',
    t10: 'Mapping ideas.',
    t11: 'Building worlds.',
    t12: 'Give ideas a sense of place.',
    t13: 'Explore my work',
    t14: 'View resume',
    t15: 'SCROLL TO EXPLORE',
    t16: 'Map development',
    t17: 'DATA',
    t18: 'Visualization',
    t19: 'FULL STACK',
    t20: 'Always exploring',
    t21: 'GEOSPATIAL THINKING',
    t22: '01 / Selected work',
    t23: 'Real problems.',
    t24: 'Spatial solutions.',
    t25: '01 — HAINAN / SURVEY',
    t26: 'Explore project',
    t27: 'More projects',
    t28: 'projects',
    t29: 'BUILT FOR REAL-WORLD CHALLENGES.',
    t30: 'Every project is an exploration.',
    t31: '02 / A little about me',
    t32: 'Curiosity is',
    t33: 'my ',
    t34: 'compass.',
    t35: 'Starting with maps, building toward complete solutions.',
    t36: 'Nov 2024 — Present',
    t37: 'WebGIS Developer',
    t38: 'Hubei Jiakuan Technology Co., Ltd.',
    t39: 'On site at Hainan Bureau of Surveying and Geoinformation',
    t40: 'Jul — Sep 2022',
    t41: 'WebGIS Development Intern',
    t42: 'Wuhan Zhongdi Digital Technology Co., Ltd.',
    t43: 'EDUCATION',
    t44: 'Hubei University',
    t45: 'BSc in Geographic Information Science · Class of 2023',
    t46: 'Maps & spatial data',
    t47: 'Frontend & visualization',
    t48: 'Backend & engineering · Learning',
    t49: '03 / Have something in mind?',
    t50: 'Let’s ',
    t51: 'connect.',
    t52: 'Let’s talk',
    t53: 'Enshi, Hubei',
    t54: 'Download resume ↓',
    t55: 'WeChat QR code ＋',
    t56: 'Jinlong’s WeChat QR code',
    t57: '© 2026 曹进龙',
    t58: 'BUILT WITH CURIOSITY. MAPPED WITH CARE.',
    p0: 'Hello, I’m Jinlong Cao. I build WebGIS applications, 3D maps and data visualizations, connecting spatial data to the real world and exploring full-stack GIS.',
    p1: 'From spatial data to real use cases, turning complex problems into clear product experiences.',
    p2: 'A Geographic Information Science graduate of Hubei University, focused on WebGIS frontend development, 2D and 3D maps, spatial visualization and complex business interactions.',
    p3: 'Currently learning and applying Java, Spring Boot and MyBatis to deliver solutions spanning map applications, backend services and spatial data.',
    p4: 'Let your next idea take shape on a map. Open to conversations about WebGIS, 3D visualization and collaboration.',
    features: {
      1: {
        category: 'WEBGIS · DATA VISUALIZATION',
        headline: 'Survey resources. One clear map.',
        intro:
          'The Hainan survey network system brings agencies, disciplines and regional data together on one map.'
      },
      3: {
        category: '02 / 3D GIS · SPATIAL ANALYSIS',
        headline: 'Bring spatial analysis into 3D.',
        intro:
          'Interactive terrain analysis, map annotations and spatial exploration for the Hainan 3D project.'
      },
      5: {
        category: '03 / WEB APPLICATION · KNOWLEDGE',
        headline: 'Expert knowledge within reach.',
        intro:
          'Documents, courses and Q&A in one place for cadastral knowledge management and learning.'
      }
    }
  }
}
